/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ATest;

import java.awt.Color;

/**
 *
 * @author nadee
 */
public class updateCustomers extends javax.swing.JFrame {

    /**
     * Creates new form updateCustomers
     */
    public updateCustomers() {
        initComponents();
        this.setBackground(new Color(1.0f, 1.0f, 1.0f, 0.0f));
        this.setLocationRelativeTo(null);

        buttonGroup1.add(cusTitlejRadioButton1);
        buttonGroup1.add(cusTitlejRadioButton2);
        buttonGroup1.add(cusTitlejRadioButton3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        updateCusjLabel2 = new javax.swing.JLabel();
        CusTitlejLabel3 = new javax.swing.JLabel();
        cusNamejLabel4 = new javax.swing.JLabel();
        cusAddressjLabel5 = new javax.swing.JLabel();
        CusCityjLabel6 = new javax.swing.JLabel();
        CusProvincejLabel7 = new javax.swing.JLabel();
        cusPostaalCodejLabel8 = new javax.swing.JLabel();
        cusPostalCode = new javax.swing.JTextField();
        cusProvince = new javax.swing.JTextField();
        CusCity = new javax.swing.JTextField();
        cusAddress = new javax.swing.JTextField();
        cusName = new javax.swing.JTextField();
        cusTitlejRadioButton1 = new javax.swing.JRadioButton();
        cusTitlejRadioButton2 = new javax.swing.JRadioButton();
        updateCustomerjButton1 = new javax.swing.JButton();
        LogoutjButton2 = new javax.swing.JButton();
        backjButton3 = new javax.swing.JButton();
        cusTitlejRadioButton3 = new javax.swing.JRadioButton();
        CusContactNumjLabel9 = new javax.swing.JLabel();
        cusContactNumber = new javax.swing.JTextField();
        cusNICjLabel10 = new javax.swing.JLabel();
        CusNIC = new javax.swing.JTextField();
        cusEmailjLabel11 = new javax.swing.JLabel();
        cusEmailAddress = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 460));

        updateCusjLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        updateCusjLabel2.setForeground(new java.awt.Color(51, 102, 255));
        updateCusjLabel2.setText("UPDATE CUSTOMER");

        CusTitlejLabel3.setText("TITLE :");

        cusNamejLabel4.setText("NAME :");

        cusAddressjLabel5.setText("ADDRESS :");

        CusCityjLabel6.setText("CITY :");

        CusProvincejLabel7.setText("PROVINCE :");

        cusPostaalCodejLabel8.setText("POSTAL CODE :");

        cusPostalCode.setForeground(new java.awt.Color(204, 204, 204));
        cusPostalCode.setText("Postal Code");
        cusPostalCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cusPostalCodecusPostalFocusGained(evt);
            }
        });
        cusPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusPostalCodeActionPerformed(evt);
            }
        });

        cusProvince.setForeground(new java.awt.Color(204, 204, 204));
        cusProvince.setText("Province");
        cusProvince.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cusProvinceFocusGained(evt);
            }
        });

        CusCity.setForeground(new java.awt.Color(204, 204, 204));
        CusCity.setText("City");
        CusCity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CusCitycityFocusGained(evt);
            }
        });

        cusAddress.setForeground(new java.awt.Color(204, 204, 204));
        cusAddress.setText("Address");
        cusAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cusAddressaddressFocusGained(evt);
            }
        });
        cusAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusAddressActionPerformed(evt);
            }
        });

        cusName.setForeground(new java.awt.Color(204, 204, 204));
        cusName.setText("Name");
        cusName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cusNameFocusGained(evt);
            }
        });
        cusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusNameActionPerformed(evt);
            }
        });

        cusTitlejRadioButton1.setText("Mr");

        cusTitlejRadioButton2.setText("Mrs");

        updateCustomerjButton1.setText("UPDATE");
        updateCustomerjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCustomerjButton1ActionPerformed(evt);
            }
        });

        LogoutjButton2.setText("LOGOUT");

        backjButton3.setText("BACK");

        cusTitlejRadioButton3.setText("Rev");

        CusContactNumjLabel9.setText("CONTACT NUMBER :");

        cusContactNumber.setForeground(new java.awt.Color(204, 204, 204));
        cusContactNumber.setText("Contact Number");
        cusContactNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cusContactNumbercontactNumFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cusContactNumbercontactNumberFocusLost(evt);
            }
        });
        cusContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusContactNumberActionPerformed(evt);
            }
        });

        cusNICjLabel10.setText("NIC :");

        CusNIC.setForeground(new java.awt.Color(204, 204, 204));
        CusNIC.setText("NIC Number");
        CusNIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CusNICNICFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CusNICNICFocusLost(evt);
            }
        });
        CusNIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusNICActionPerformed(evt);
            }
        });

        cusEmailjLabel11.setText("E- MAIL :");

        cusEmailAddress.setForeground(new java.awt.Color(204, 204, 204));
        cusEmailAddress.setText("Email");
        cusEmailAddress.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cusEmailAddressemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cusEmailAddresscusEmailfocusLost(evt);
            }
        });
        cusEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusEmailAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cusNICjLabel10)
                            .addComponent(cusEmailjLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusNamejLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CusTitlejLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cusTitlejRadioButton1)
                                .addGap(27, 27, 27)
                                .addComponent(cusTitlejRadioButton2)
                                .addGap(18, 18, 18)
                                .addComponent(cusTitlejRadioButton3))
                            .addComponent(cusEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cusName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(CusNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(CusContactNumjLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(cusContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updateCusjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(220, 220, 220)
                        .addComponent(backjButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LogoutjButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CusCityjLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cusPostaalCodejLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                            .addComponent(cusAddressjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateCustomerjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(CusCity, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(CusProvincejLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cusProvince, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                                .addComponent(cusAddress)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(updateCusjLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backjButton3)
                        .addComponent(LogoutjButton2)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusTitlejLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusTitlejRadioButton1)
                    .addComponent(cusTitlejRadioButton2)
                    .addComponent(cusTitlejRadioButton3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusNamejLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cusNICjLabel10))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CusContactNumjLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CusNIC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cusContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusEmailjLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cusAddressjLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CusProvincejLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cusProvince, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CusCity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CusCityjLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cusPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cusPostaalCodejLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(updateCustomerjButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cusPostalCodecusPostalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusPostalCodecusPostalFocusGained
        // TODO add your handling code here:
        cusPostalCode.setForeground(Color.BLACK);
        cusPostalCode.setText("");
    }//GEN-LAST:event_cusPostalCodecusPostalFocusGained

    private void cusPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusPostalCodeActionPerformed

    private void cusProvinceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusProvinceFocusGained
        // TODO add your handling code here:
        cusProvince.setForeground(Color.BLACK);
        cusProvince.setText("");
    }//GEN-LAST:event_cusProvinceFocusGained

    private void CusCitycityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CusCitycityFocusGained
        // TODO add your handling code here:
        CusCity.setForeground(Color.BLACK);
        CusCity.setText("");
    }//GEN-LAST:event_CusCitycityFocusGained

    private void cusAddressaddressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusAddressaddressFocusGained
        // TODO add your handling code here:
        cusAddress.setForeground(Color.BLACK);
        cusAddress.setText("");
    }//GEN-LAST:event_cusAddressaddressFocusGained

    private void cusAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusAddressActionPerformed

    private void cusNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusNameFocusGained
        // TODO add your handling code here:
        cusName.setForeground(Color.BLACK);
        cusName.setText("");
    }//GEN-LAST:event_cusNameFocusGained

    private void cusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusNameActionPerformed

    private void updateCustomerjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCustomerjButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateCustomerjButton1ActionPerformed

    private void cusContactNumbercontactNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusContactNumbercontactNumFocusGained
        // TODO add your handling code here:
        cusContactNumber.setForeground(Color.BLACK);
        cusContactNumber.setText("");
    }//GEN-LAST:event_cusContactNumbercontactNumFocusGained

    private void cusContactNumbercontactNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusContactNumbercontactNumberFocusLost
        // TODO add your handling code here:
        final String CONTACT_NUMBER_PATTERN = "0\\d{9}";
        final String CONTACT_NUMBER_PATTERN2 = "+94\\d{9}";

        String contact = cusContactNumber.getText();
        boolean contactCheck = contact.matches(CONTACT_NUMBER_PATTERN)
        || contact.matches(CONTACT_NUMBER_PATTERN2);

        if (!contactCheck) {
            cusContactNumber.setForeground(Color.red);
        };
    }//GEN-LAST:event_cusContactNumbercontactNumberFocusLost

    private void cusContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusContactNumberActionPerformed

    private void CusNICNICFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CusNICNICFocusGained
        // TODO add your handling code here:
        CusNIC.setForeground(Color.BLACK);
        CusNIC.setText("");
    }//GEN-LAST:event_CusNICNICFocusGained

    private void CusNICNICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CusNICNICFocusLost
        // TODO add your handling code here:
        final String NIC_PATTERN_1 = "\\d{9}+V";
        final String NIC_PATTERN_2 = "\\d{9}+v";
        final String NIC_PATTERN_3 = "\\d{9}+X";
        final String NIC_PATTERN_4 = "\\d{9}+x";
        final String NIC_PATTERN_5 = "\\d{12}";

        String nic = CusNIC.getText();
        boolean nicCheck = nic.matches(NIC_PATTERN_1) || nic.matches(NIC_PATTERN_2)
        || nic.matches(NIC_PATTERN_3) || nic.matches(NIC_PATTERN_4)
        || nic.matches(NIC_PATTERN_5);

        if (!nicCheck) {
            CusNIC.setForeground(Color.red);
        };
    }//GEN-LAST:event_CusNICNICFocusLost

    private void CusNICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusNICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusNICActionPerformed

    private void cusEmailAddressemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusEmailAddressemailFocusGained
        // TODO add your handling code here:
        cusEmailAddress.setForeground(Color.BLACK);
        cusEmailAddress.setText("");
    }//GEN-LAST:event_cusEmailAddressemailFocusGained

    private void cusEmailAddresscusEmailfocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cusEmailAddresscusEmailfocusLost
        // TODO add your handling code here:
        final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

        String email = cusEmailAddress.getText();

        if (!email.matches(EMAIL_PATTERN)) {
            cusEmailAddress.setForeground(Color.red);
        };
    }//GEN-LAST:event_cusEmailAddresscusEmailfocusLost

    private void cusEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusEmailAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CusCity;
    private javax.swing.JLabel CusCityjLabel6;
    private javax.swing.JLabel CusContactNumjLabel9;
    private javax.swing.JTextField CusNIC;
    private javax.swing.JLabel CusProvincejLabel7;
    private javax.swing.JLabel CusTitlejLabel3;
    private javax.swing.JButton LogoutjButton2;
    private javax.swing.JButton backjButton3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cusAddress;
    private javax.swing.JLabel cusAddressjLabel5;
    private javax.swing.JTextField cusContactNumber;
    private javax.swing.JTextField cusEmailAddress;
    private javax.swing.JLabel cusEmailjLabel11;
    private javax.swing.JLabel cusNICjLabel10;
    private javax.swing.JTextField cusName;
    private javax.swing.JLabel cusNamejLabel4;
    private javax.swing.JLabel cusPostaalCodejLabel8;
    private javax.swing.JTextField cusPostalCode;
    private javax.swing.JTextField cusProvince;
    private javax.swing.JRadioButton cusTitlejRadioButton1;
    private javax.swing.JRadioButton cusTitlejRadioButton2;
    private javax.swing.JRadioButton cusTitlejRadioButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel updateCusjLabel2;
    private javax.swing.JButton updateCustomerjButton1;
    // End of variables declaration//GEN-END:variables
}
